openai_api_key: 
TOGETHER_API_KEY: b02cf03eec2570be89f0acd0685e64bcf09362eadf27009195f6ee898bc00e39
use_together: true  # If true, we call Together. If false, we call OpenAI.

agents:
  pdf2latex:
    default_model: "gpt-3.5-turbo"   # For OpenAI
    system_prompt: "You are a helpful assistant specialized in reading LaTeX documents."
    user_prompt: "Can you summarize this PDF for me?"
    together_model: "meta-llama/Llama-3.3-70B-Instruct-Turbo"  # For Together
